[phases.setup]
nixPkgs = ['nodejs_20', 'python313']

[phases.install]
cmds = [
  'npm install',
  'python -m venv /opt/venv',
  'source /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
