[build]
builder = "nixpacks"
buildCommand = "/opt/venv/bin/pip install -r requirements.txt && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
